module.exports = Object.freeze({
  RET_CONTEXT_TTL: "PT30S",
  RET_CONTEXT_ACTION: "action",
  DB_PATH: "dbfiles",
  RET_SEARCH: "search",
  RET_ONSEARCH: "on_search",
  RET_SELECT: "select",
  RET_ONSELECT: "on_select",
  RET_INIT: "init",
  RET_ONINIT: "on_init",
  RET_CONFIRM: "confirm",
  RET_ONCONFIRM: "on_confirm",
  RET_TRACK: "track",
  RET_ONTRACK: "on_track",
  RET_CANCEL: "cancel",
  RET_ONCANCEL: "on_cancel",
  RET_UPDATE: "update",
  RET_ONUPDATE: "on_update",
  RET_STATUS: "status",
  RET_ONSTATUS: "on_status",
  RET_SUPPORT: "support",
  RET_ONSUPPORT: "on_support",
});
